### ISSUE TITLE
Issue with "No Formatting" Toggle Repeating LoRA in Prompt

### ISSUE THREAD

**Issue by MondayMonkey1** [KohakuBlueleaf/z-tipo-extension#24]
Hi,
Whenever I toggle "No formatting," TIPO seems to repeat the LoRA(s) in the prompt.(It worked on DTG though.)

For example, if a prompt is like this:
"1girl, [lora-name-here:1.0], character name"
The TIPO output becomes:
"1girl, [lora-name-here:1.0], character name, [lora-name-here:1.0]"
which ruins the generated image because of the duplication of the exact same LoRA.
I also found that unchecking the "No formatting" box fixes this issue.

Please check.
Thanks.

**Comment by KohakuBlueleaf** [comment]
investigating

**Comment by KohakuBlueleaf** [comment]
I think this issue is somehow fixed with new kgen lib
try to update the kgen lib with `python -m pip install -U tipo-kgen`

**Comment by MondayMonkey1** [comment]
Thanks!
Although I executed "python -m pip install -U tipo-kgen" and confirmed that its version is 0.1.5, which I believe is the latest one, the issue is still occurring.

**Comment by KohakuBlueleaf** [comment]
You should also try to update the extension as well

**Comment by MondayMonkey1** [comment]
I already tried updating and re-installing TIPO extension.
