### ISSUE TITLE
Installing in MPS(Metal)

### ISSUE THREAD

**Issue by Kiriki-liszt** [KohakuBlueleaf/z-tipo-extension#78]
Hi! 
Thanks for developing nice tool!

I had a problem installing this node in Apple MPS(Metal) environment;

- iMac 24 M3 macOS 15.3.2  
- ComfyUI v0.4.32 standalone app  

The line 
``` python
torch.version.cuda.replace(".", "")
``` 
is not executable if cuda is not able, so I just added simple 
``` python
if has_cuda:
```
above it. 

While installing llama_cpp_python, be careful not to use pip. It must run in pip3.  
``` bash
source 'PATH_TO_YOUR/ComfyUI/.venv/bin/activate'
CMAKE_ARGS="-DGGML_METAL=on" pip3 install llama-cpp-python
```

After that, this node worked fine!
Hope there's a way to automatically support this process =)

**Comment by KohakuBlueleaf** [comment]
Will check it more carefully!
My environment have "python" and "pip" since I use micromamba... forget I should check the sys.executable

**Comment by KohakuBlueleaf** [comment]
Fixed in 68ed828

**Comment by CamilleHbp** [comment]
Nope, the problem is still there, it fails installation because of Cuda.

```
[TIPO-KGen-installer]-|10:03:31|-INFO: Attempting to install LLaMA-CPP-Python
Traceback (most recent call last):
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/nodes.py", line 2149, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/camille/ComfyUI/custom_nodes/z-tipo-extension/__init__.py", line 1, in <module>
    from .nodes.tipo import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/Users/camille/ComfyUI/custom_nodes/z-tipo-extension/nodes/tipo.py", line 11, in <module>
    install_llama_cpp()
  File "/Users/camille/ComfyUI/custom_nodes/z-tipo-extension/tipo_installer.py", line 119, in install_llama_cpp
    cuda_version = torch.version.cuda.replace(".", "")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by KohakuBlueleaf** [comment]
> Honestly, I don't understand why you are trying to install a package directly from code? Is it something specific to comfyui nodes? Otherwise you should add it to the requirements, not install it from code — here in `uv`, it's `pyproject.toml`.

1. Requirements system not allow non standard packaging choice system like hardware specific builds
2. Sd webui(or reforge/forge) will not install requirements.txt directly 
3. User prefer prebuilt wheel while llama-cpp-python doesn't have good prebuilt wheels and never publish to pypi with proper tag
